#why Numpy
To conclude it's because it's faster for the operations and because of it's usage.

#Importing
we need to import it first before everything


In [ ]:
import numpy as np

#Assuming that we have a list called 'first_list'

#converting
converting a ist to an array


In [ ]:
first_list = [1,3,5,7]
np.array(first_list)

array([1, 3, 5, 7])

#converting - 2
converting a matrix to an array

In [ ]:
matrix = [[1,1,1],[2,2,2],[3,3,3]]
np.array (matrix)

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

#**Built-in Methods**
There are lots of built-in ways to generate Arrays

# arange
Return evenly spaced values within a given interval.

بترجع العناصر من البدايه للعنصر قبل الاخير

In [ ]:
np.arange(0,7)

array([0, 1, 2, 3, 4, 5, 6])

### If we pay attention here, he took the penultimate element, not the last

لو اخدنا بالنا هنا هو وصل لحد العنصر قبل الاخير مش
الاخير

#stepping
we can use it with an extra parameter for stepping

In [ ]:
np.arange (0,7,2)

array([0, 2, 4, 6])

#zeros and ones
Generate arrays of zeros or ones

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.zeros((3,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.ones((3,3,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

#linspace
Return evenly spaced numbers over a specified interval.

 بيجيب ارقام ما بين الرقمين اللي حاطيناهم وممكن اضيف عددهم في الاخر


In [ ]:
np.linspace(0,2,5)

array([0. , 0.5, 1. , 1.5, 2. ])

In [ ]:
np.linspace(0,4,2)

array([0., 4.])

#eye
Creates an identity matrix

In [ ]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#Random
Numpy also has lots of ways to create random number arrays:

#rand
Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1].

In [ ]:
np.random.rand(4)

array([0.07921534, 0.6498535 , 0.28591563, 0.93454342])

In [ ]:
np.random.rand(2,2)

array([[0.29335721, 0.99735706],
       [0.90848266, 0.86962721]])

In [ ]:
np.random.rand(2,3,4)

array([[[0.08833676, 0.06436636, 0.76637471, 0.17929595],
        [0.81352121, 0.57947248, 0.18956424, 0.79897556],
        [0.27172691, 0.58180236, 0.27410849, 0.39648442]],

       [[0.18666054, 0.58562689, 0.62215921, 0.44404529],
        [0.3489529 , 0.06817666, 0.09533445, 0.63981087],
        [0.12612924, 0.71557585, 0.30168393, 0.83295367]]])

#randn
Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform

In [ ]:
np.random.randn(2)

array([-0.55400129,  0.01538467])

In [ ]:
np.random.randn(2,2)

array([[ 1.43365005, -0.05213978],
       [-1.8525898 ,  0.72702158]])

#randint
Return random integers from low (inclusive) to high

In [ ]:
np.random.randint(1,50)

35

In [ ]:
np.random.randint(5,10)

9

In [ ]:
np.random.randint(1,1000,10)

array([893, 734, 336, 185, 881, 949, 274, 191, 959, 900])

#Reshape
Returns an array containing the same data with a new shape.

In [ ]:
arr = np.arange(10)

In [ ]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

#max,min,argmax,argmin
These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [ ]:
arr =np.arange(0,20)

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
arr.max()

19

In [ ]:
arr.min()

0

In [ ]:
arr.argmax()

19

In [ ]:
arr.argmin()

0

#Shape
Shape is an attribute that arrays have (not a method):

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
arr = np.arange(6)

In [ ]:
arr

array([0, 1, 2, 3, 4, 5])

In [ ]:
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
arr.reshape(2,3).shape

(2, 3)

#dtype
You can also grab the data type of the object in the array:

In [ ]:
arr.dtype

dtype('int64')

#Bracket Indexing and Selection
The simplest way to pick one or some elements of an array looks very similar to python lists:

In [ ]:
arr

array([0, 1, 2, 3, 4, 5])

In [ ]:
arr[0]

0

In [ ]:
arr[5]

5

In [ ]:
arr[0:5]

array([0, 1, 2, 3, 4])

#Broadcasting
Numpy arrays differ from a normal Python list because of their ability to broadcast:

In [ ]:
arr

array([0, 1, 2, 3, 4, 5])

In [ ]:
arr[0]=65

In [ ]:
arr

array([65,  1,  2,  3,  4,  5])

In [ ]:
arr[1]=66

In [ ]:
arr

array([65, 66,  2,  3,  4,  5])

In [ ]:
arr[0:6]=100

In [ ]:
arr

array([100, 100, 100, 100, 100, 100])

In [ ]:
arr = np.arange(0,5)

In [ ]:
arr

array([0, 1, 2, 3, 4])

In [ ]:
slice_of_arr = arr[0:2]
slice_of_arr

array([0, 1])

In [ ]:
slice_of_arr[:]=99
slice_of_arr

array([99, 99])

Now note the changes also occur in our original array!

In [ ]:
arr

array([99, 99,  2,  3,  4])

#NumPy Operations
Arithmetic
You can easily perform array with array arithmetic, or scalar with array arithmetic. Let's see some examples

In [ ]:
import numpy as np
arr = np.arange(0,10)

In [ ]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [ ]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
arr/arr

<ipython-input-107-50b4ced5627e>:1: RuntimeWarning: invalid value encountered in divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

#Warning on division by zero, but not an error!
Just replaced with nan

In [ ]:
arr**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

#Universal Array Functions
Numpy comes with many universal array functions, which are essentially just mathematical operations you can use to perform the operation across the array. Let's show some common ones

In [ ]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [ ]:
np.max(arr) #same as arr.max()

9

#Thanks !!
Hope these was good for you!